#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

VERSION="7.5.0"
URL="https://sourceforge.net/projects/vtigercrm/files/vtiger%20CRM%20$VERSION/Core%20Product/vtigercrm$VERSION.tar.gz/download"

dl $URL /usr/local/src
